### ISSUE TITLE
feat: support formatting of the JSON file

### ISSUE THREAD

**Issue by LandonLoo** [vladimiry/fs-json-store#13]
Is there an option for JSON formatting? It would be great if there is one. The idea is to make the file more human readable like package.json.

**Comment by vladimiry** [comment]
You can override a serializer by specifying `serialize` function in the options.

The default function looks like:
`((data) => Buffer.from(JSON.stringify(data)))`

and you could pass something like:
`((data) => Buffer.from(JSON.stringify(data, null, 2)))`

https://github.com/vladimiry/fs-json-store/blob/dcb890aa7087d4413f4359191f8071755f0bdf99/src/lib/private/store.ts#L24

**Comment by LandonLoo** [comment]
Any plan on updating the documentation in README.md, as `serialize`, `deserialize` & `lockfileRealpath` are not listed in the `options` under `constructor(options)`? 😃

**Comment by vladimiry** [comment]
No such plans at the moment. Consider it as a pleasant surprise :smiley:
