### ISSUE TITLE
Question: Is this production ready?

### ISSUE THREAD

**Issue by johannesjo** [vladimiry/fs-json-store#3]
Sorry for asking something like this here, but the repo didn't get much attention, and sometimes that points to a problem or a lack of maturity. Looks pretty promising to me though so far. Do you plan to work on this in the future?

**Comment by vladimiry** [comment]
> Do you plan to work on this in the future?

There is no plan for extending the functionality. The module is being maintained to the extent that https://github.com/vladimiry/ElectronMail project doesn't suffer much since that's the project the module was originally built for use by.

**Comment by johannesjo** [comment]
Thank you very much for letting me know!

I wonder why this never was promoted. Would you mind me posting this on reddit?

**Comment by vladimiry** [comment]
> I wonder why this never was promoted. Would you mind me posting this on reddit?

I didn't see a need to promote the module. If you do I can't prevent you from doing this.

**Comment by vladimiry** [comment]
By the way take a look at https://github.com/sindresorhus/conf which is more widely used and so potentially more mature module. It does atomic write using https://github.com/fabiospampinato/atomically.

**Comment by johannesjo** [comment]
Thank you very much for the tip! I will look into those.

**Comment by vladimiry** [comment]
Closing as resolved.
